### ISSUE TITLE
LUCID dataset

### ISSUE THREAD

**Issue by laqangela** [NJUVISION/rho-vision#11]
请问可以再分享一下LUCID数据集，百度盘链接过期了。谢谢！

**Comment by lizhihao6** [comment]
您好，感谢关注我们的工作，重新共享给您链接了，祝好。

【超级会员V1】通过百度网盘分享的文件：LUCID_TR…
链接:https://pan.baidu.com/s/1p2yjfJgB_vGT3R3N_8g3aw
提取码:x2un
复制这段内容打开「百度网盘APP 即可获取」



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Anqi Liu ***@***.***>
Sent: Tuesday, June 11, 2024 10:07:12 AM
To: NJUVISION/rho-vision ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NJUVISION/rho-vision] LUCID dataset (Issue #11)


请问可以再分享一下LUCID数据集，百度盘链接过期了。谢谢！

―

**Comment by lizhihao6** [comment]
Hi thx for reaching out, I have updated the LUCID downloading link.

**Comment by laqangela** [comment]
Thx soooo much！！

**Comment by ChaiJohn216** [comment]
非常感谢您再次开放LUCID下载链接，我解压后发现oficial isp文件夹中的图片如下，看起来色彩不太正常，或者有被削峰的像素点，请问这是论文中所提AX620A ISP处理后的效果吗？是否是由于数据采集过程中相机参数设置造成的呢？
![Screenshot from 2024-06-14 15-35-37](https://github.com/NJUVISION/rho-vision/assets/128793993/55116c33-831d-4562-b9c6-00e44ed726f9)
![Screenshot from 2024-06-14 15-35-41](https://github.com/NJUVISION/rho-vision/assets/128793993/73c0cdf3-26b4-45fb-99b5-f3a25ce08cf2)

**Comment by lizhihao6** [comment]
official isp 是 lucid isp直出效果

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
