### ISSUE TITLE
multiRAW里的文件没有train.txt

### ISSUE THREAD

**Issue by Chegva** [NJUVISION/rho-vision#2]
你好，我下载了你们的multiRAW数据集和代码，运行代码的时候报错了说没有train.txt文件，然后我打开数据集文件发现multiRAW文件里的几个文件夹里面没有train.txt，但是rho-vision-main/configs/_base_/datasets/bdd100k_rgb2asi_raw_512x512.py文件里，却需要train.txt，请问这是要自己制作吗，如果是的话，要如何制作呢。

**Comment by lizhihao6** [comment]
您好，稍后我会验证一下 zip，缺少的话我会补充上传

**Comment by lizhihao6** [comment]
您好，我这边看起来是含有 train.txt 和 test.txt 的，请问您用的是哪几个zip，怎样合并的？

**Comment by Chegva** [comment]
hello，我看南京大学网盘里的那个数据集里，huawei_p30pro的压缩文件，少了5，6，7，8卷，是否有漏传呢

**Comment by lizhihao6** [comment]
已补传
