### ISSUE TITLE
inference.py中的代码问题

### ISSUE THREAD

**Issue by JustQJ** [NJUVISION/rho-vision#4]
你好，很荣幸阅读到你的工作。在inference.py的`DemoModel`类中的`_mosaic`函数是否有一些问题，抽取rggb域的数据的形式或许应该是
```
_x[:, 0] = x[:, 0, 0::2, 0::2]
_x[:, 1] = x[:, 1, 0::2, 1::2]
_x[:, 2] = x[:, 1, 1::2, 0::2]
_x[:, 3] = x[:, 2, 1::2, 1::2]
```
而不是
```
 _x[:, 0] = x[:, 0, 0::2, 0::2]
 _x[:, 1] = x[:, 0, 1::2, 0::2]
 _x[:, 2] = x[:, 0, 0::2, 1::2]
 _x[:, 3] = x[:, 0, 1::2, 1::2]
```
谢谢

**Comment by lizhihao6** [comment]
您好，是的，这里是我们typo了，我将尽快修改。感谢。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: JustQJ ***@***.***>
发送时间: Saturday, February 18, 2023 11:02:51 AM
收件人: NJUVISION/rho-vision ***@***.***>
抄送: Subscribed ***@***.***>
主题: [NJUVISION/rho-vision] inference.py中的代码问题 (Issue #4)


你好，很荣幸阅读到你的工作。在inference.py的DemoModel类中的_mosaic函数是否有一些问题，抽取rggb域的数据的形式或许应该是

_x[:, 0] = x[:, 0, 0::2, 0::2]

_x[:, 1] = x[:, 1, 0::2, 1::2]

_x[:, 2] = x[:, 1, 1::2, 0::2]

_x[:, 3] = x[:, 2, 1::2, 1::2]



而不是

 _x[:, 0] = x[:, 0, 0::2, 0::2]

 _x[:, 1] = x[:, 0, 1::2, 0::2]

 _x[:, 2] = x[:, 0, 0::2, 1::2]

 _x[:, 3] = x[:, 0, 1::2, 1::2]



谢谢

―
