### ISSUE TITLE
training yolov3 with simraw dataset

### ISSUE THREAD

**Issue by cverrr** [NJUVISION/rho-vision#5]
How to get the label of the generated simraw data set

**Comment by cverrr** [comment]
simRAWb的标签是手动标的吗

**Comment by lizhihao6** [comment]
谢谢您对我们工作的关注。

关于您提到的问题，我们生成的 simraw 数据集的标签是使用对应的 RGB  标签。如果您输入网络时使用的是重排列为四通道的 RAW image，则需要将边界框（bbox）的大小调整为原来的一半。

**Comment by cverrr** [comment]
谢谢您的解答，我认为您的工作很有意义。
